//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 11:36:20 PM on Wednesday, May 19, 2004
//
//	Generated for file: C:\My Projects\PalmDev\HACCP2002\Rsc\HACCP2002.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"HACCP 2004"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainUnnamed1003BitMap                     0	//(Left Origin = 68, Top Origin = 74, Bitmap Resource ID = 0, Usable = 1)
#define MainCopyrightField                        1005	//(Left Origin = 26, Top Origin = 34, Width = 110, Height = 36, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainTitleLabel                            1001	//(Left Origin = 20, Top Origin = 22, Usable = 1, Font = Bold)
#define MainHaccpLabelLabel                       1002	//(Left Origin = 37, Top Origin = 103, Usable = 1, Font = Bold 12)
#define MainTempLabelLabel                        1004	//(Left Origin = 25, Top Origin = 118, Usable = 1, Font = Large)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 135, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1106BitMap                    0	//(Left Origin = 68, Top Origin = 62, Bitmap Resource ID = 0, Usable = 1)
#define AboutCopyrightField                       1104	//(Left Origin = 26, Top Origin = 25, Width = 110, Height = 36, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define AboutTitleLabel                           1101	//(Left Origin = 20, Top Origin = 13, Usable = 1, Font = Bold)
#define AboutHaccpLabelLabel                      1102	//(Left Origin = 37, Top Origin = 88, Usable = 1, Font = Bold 12)
#define AboutTempLabelLabel                       1103	//(Left Origin = 25, Top Origin = 103, Usable = 1, Font = Large)

//	Resource: tFRM 1200
#define SelectionsForm                            1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define SelectionsHaccpLabelLabel                 1201	//(Left Origin = 37, Top Origin = 0, Usable = 1, Font = Bold 12)
#define SelectionsTempLabelLabel                  1202	//(Left Origin = 25, Top Origin = 15, Usable = 1, Font = Large)
#define SelectionsReceivingPushButton             1203	//(Left Origin = 2, Top Origin = 60, Width = 72, Height = 18, Usable = 1, Group ID = 0, Font = Standard)
#define SelectionsEquipmentPushButton             1204	//(Left Origin = 86, Top Origin = 60, Width = 72, Height = 18, Usable = 1, Group ID = 0, Font = Standard)
#define SelectionsButton1PushButton               1205	//(Left Origin = 2, Top Origin = 91, Width = 72, Height = 18, Usable = 1, Group ID = 0, Font = Standard)
#define SelectionsButton3PushButton               1206	//(Left Origin = 86, Top Origin = 91, Width = 72, Height = 18, Usable = 1, Group ID = 0, Font = Standard)
#define SelectionsButton2PushButton               1207	//(Left Origin = 2, Top Origin = 121, Width = 72, Height = 18, Usable = 1, Group ID = 0, Font = Standard)
#define SelectionsButton4PushButton               1208	//(Left Origin = 86, Top Origin = 121, Width = 72, Height = 18, Usable = 1, Group ID = 0, Font = Standard)

//	Resource: tFRM 1300
#define ItemsForm                                 1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ItemsLocationButton                       1305	//(Left Origin = 26, Top Origin = 27, Width = 112, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Bold)
#define ItemsHiddenField                          1309	//(Left Origin = 154, Top Origin = 143, Width = 6, Height = 12, Usable = 1, Editable = 1, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define ItemsHaccpLabelLabel                      1301	//(Left Origin = 39, Top Origin = 0, Usable = 1, Font = Bold 12)
#define ItemsTempLabelLabel                       1302	//(Left Origin = 21, Top Origin = 15, Usable = 1, Font = Standard)
#define ItemsUnnamed1306Label                     1306	//(Left Origin = 4, Top Origin = 45, Usable = 1, Font = Standard)
#define ItemsUnnamed1307Label                     1307	//(Left Origin = 82, Top Origin = 45, Usable = 1, Font = Standard)
#define ItemsUnnamed1308Label                     1308	//(Left Origin = 111, Top Origin = 45, Usable = 1, Font = Standard)
#define ItemsFoodList                             1304	//(Left Origin = 4, Top Origin = 58, Width = 150, Usable = 1, Font = Standard, Visible Items = 7)
#define ItemsBackGraphicButton                    1303	//(Left Origin = 6, Top Origin = 139, Width = 42, Height = 17, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Bitmap Resource ID = 1000, Selected Bitmap Resource ID = 1000)

//	Resource: tFRM 1400
#define SeverityForm                              1400	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define SeverityOkButton                          1403	//(Left Origin = 61, Top Origin = 144, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define SeverityFoodButton                        1405	//(Left Origin = 38, Top Origin = 57, Width = 84, Height = 12, Usable = 1, Anchor Left = 1, Frame = 0, Non-bold Frame = 1, Font = Standard)
#define SeverityTempField                         1410	//(Left Origin = 73, Top Origin = 119, Width = 20, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define SeverityDegreesField                      1412	//(Left Origin = 93, Top Origin = 119, Width = 20, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define SeverityHaccpLabelLabel                   1401	//(Left Origin = 37, Top Origin = 0, Usable = 1, Font = Bold 12)
#define SeverityTempLabelLabel                    1402	//(Left Origin = 25, Top Origin = 15, Usable = 1, Font = Large)
#define SeverityUnnamed1404Label                  1404	//(Left Origin = 2, Top Origin = 122, Usable = 1, Font = Bold)
#define SeverityUnnamed1406Label                  1406	//(Left Origin = 34, Top Origin = 43, Usable = 1, Font = Bold)
#define SeverityUnnamed1407Label                  1407	//(Left Origin = 2, Top Origin = 77, Usable = 1, Font = Bold)
#define SeverityNotesList                         1408	//(Left Origin = 2, Top Origin = 88, Width = 157, Usable = 0, Font = Standard, Visible Items = 4)
#define SeverityNotePopTrigger                    1409	//(Left Origin = 2, Top Origin = 88, Width = 157, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1408)

//	Resource: tFRM 1500
#define LoginForm                                 1500	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define LoginContinueButton                       1505	//(Left Origin = 53, Top Origin = 139, Width = 54, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define LoginHaccpLabelLabel                      1501	//(Left Origin = 37, Top Origin = 4, Usable = 1, Font = Bold 12)
#define LoginTempLabelLabel                       1502	//(Left Origin = 25, Top Origin = 19, Usable = 1, Font = Large)
#define LoginUserLabel                            1504	//(Left Origin = 54, Top Origin = 48, Usable = 1, Font = Bold 12)
#define LoginUserList                             1506	//(Left Origin = 5, Top Origin = 67, Width = 150, Usable = 1, Font = Standard, Visible Items = 6)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1300
#define InformationAlertAlert                     1300
#define InformationAlertOK                        0

//	Resource: Talt 1600
#define YesNoAlertAlert                           1600
#define YesNoAlertYes                             0
#define YesNoAlertNo                              1

//	Resource: Talt 1101
#define PalmOSVersionAlert                        1101
#define PalmOSVersionOK                           0

//	Resource: Talt 1201
#define DeviceNotPresentAlert                     1201
#define DeviceNotPresentOK                        0

//	Resource: Talt 1301
#define FrimwareUpgradeAlert                      1301
#define FrimwareUpgradeOK                         0

//	Resource: Talt 1401
#define NotSupportedAlert                         1401
#define NotSupportedOK                            0

//	Resource: Talt 1501
#define StartupErrorAlert                         1501
#define StartupErrorOK                            0


//	Resource: MBAR 1000
#define HACCP2002MainMenuBar                      1000


//	Resource: MENU 1000
#define OptionsMenu                               1000
#define OptionsActivateDemoMode                   1000
#define OptionsAboutHACCP2004                     1001
#define OptionsExit                               1002


//	Resource: PICT 0
#define untitledBitmap                            0

//	Resource: PICT 1000
#define BackBitmap                                1000

